In [1]:
import numpy
import math

CROSS_RATE = 0.5      # mating probability
MUTATION_RATE = 0.003   # mutation probability
N_GENERATIONS = 10

# Initial Population for fitness
population = [0.35, 0.5423, 0.6744, 0.4432, 0.8523, 0.9612, 1.223, 0.756, 1.80]
Population_array = numpy.array(population)

# Calculate the fitness of population
def FitnessFunction(Population_array):
    calculation = []
    fitness = []
    for calc in Population_array:
        calculation.append(calc)
    mean_vector = numpy.mean(calculation)
    std_vector = numpy.std(calculation)

    for pop in Population_array:
        # Manhattan function
        # cur_sc = abs(mean_vector - pop) / std_vector

        # Euclidean function
        cur_sc = math.sqrt((mean_vector - pop) ** 2) / std_vector
        if cur_sc >= 0.85:
            fitness.append(cur_sc)  # Append values from population if they are more than 0.85
    return numpy.array(fitness)


# Select number of parents from population(i.e. 2 parents in this program)
# select parents randomly from fitness values and initial population
def ParentSelection(new_population, get_fitness, num_parents):
    SelectParents = numpy.empty((num_parents, new_population.shape[1]), numpy.float32)
    for parent_num in range(num_parents):
        parent_a = numpy.where(get_fitness == numpy.max(get_fitness))
        parent_a = parent_a[0][0]
        SelectParents[parent_num, :] = new_population[parent_a, :]
        get_fitness[parent_a] = -1
    return SelectParents


def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size)
    # The point at which crossover takes place between two parents. Usually, it is at the center.
    crossover_point = numpy.uint8(offspring_size[1]/2)
    for k in range(offspring_size[0]):
        check_cross_rate = numpy.random.uniform(0, 1, 1)
        if check_cross_rate <= CROSS_RATE:
            parent1 = k % parents.shape[0]    # Index of the first parent to mate.
            parent2 = (k+1) % parents.shape[0]  # Index of the second parent to mate.
            offspring[k, 0:crossover_point] = parents[parent1, 0:crossover_point]  # The new offspring will have its first half of its genes from the first parent.
            offspring[k, crossover_point:] = parents[parent2, crossover_point:]   # The new offspring will have its second half of its taken from the second parent.
    return offspring


def Mutation(offspring_crossover, num_mutations=1):
    mutations_counter = numpy.uint8(offspring_crossover.shape[1] / num_mutations)
    # Mutation changes a number of genes as defined by the
    # num_mutations argument. The changes are random.
    for idx in range(offspring_crossover.shape[0]):
        gene = mutations_counter - 1
        check_mutation_rate = numpy.random.uniform(0, 0.005, 1)
        if check_mutation_rate <= MUTATION_RATE:
            for mutation_num in range(num_mutations):
                random_value = numpy.random.uniform(0, 1, 1)   # The random value to be added to the gene.
                offspring_crossover[idx, gene] = offspring_crossover[idx, gene] + random_value
                gene = gene + mutations_counter
    return offspring_crossover


mutation_array = []
sol_per_pop = 6
num_weights = len(Population_array) % 2 + 1
# Defining the population size.size
pop_size = (sol_per_pop, num_weights)

# Creating the random population.
new_population = numpy.random.uniform(low=0, high=1, size=pop_size)


for generation in range(N_GENERATIONS):
    print("Generations :", generation)
    get_fitness = FitnessFunction(Population_array)
    fitness_result = get_fitness.max()

    # Selecting the best parents in the population for mating.
    parents = ParentSelection(new_population, get_fitness, num_parents=2)
    print("Parents")
    print(parents)

    # Generating next generation using crossover.
    offspring_crossover = crossover(parents, offspring_size=(pop_size[0]-parents.shape[0], num_weights))
    print("Crossover")
    print(offspring_crossover)

    # Adding some variations to the offspring using mutation.
    offspring_mutation = Mutation(offspring_crossover, num_mutations=2)
    mutation_array.append(offspring_mutation)
    print("Mutation")
    print(offspring_mutation)
    print()

    mutation_result = offspring_mutation.max()

    # Termination condition (if mutation result is greater than or equal to maximum value from fitness result)
    if mutation_result >= fitness_result:
        break


mutation_array = numpy.array(mutation_array)

get_fitness = FitnessFunction(Population_array)

best_fitness = numpy.where(get_fitness == numpy.max(get_fitness))

best_mutation = numpy.where(mutation_array == numpy.max(mutation_array))

print()
print("Best Mutations: ", mutation_array.max(axis=1))
print()
print("Best solution from mutations: ", mutation_array[best_mutation])
print()
print("Best solution from fitness : ", get_fitness[best_fitness])

Generations : 0
Parents
[[0.07493813 0.76172477]
 [0.81437176 0.4030058 ]]
Crossover
[[2.12199579e-314 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [7.49381334e-002 4.03005809e-001]
 [8.14371765e-001 7.61724770e-001]]
Mutation
[[2.12199579e-314 0.00000000e+000]
 [7.95316841e-001 6.28968991e-001]
 [9.56580856e-002 4.89917389e-001]
 [1.32889538e+000 8.42665104e-001]]

Generations : 1
Parents
[[0.07493813 0.76172477]
 [0.81437176 0.4030058 ]]
Crossover
[[2.12199579e-314 0.00000000e+000]
 [7.95316841e-001 6.28968991e-001]
 [7.49381334e-002 4.03005809e-001]
 [1.32889538e+000 8.42665104e-001]]
Mutation
[[0.67128412 0.2977126 ]
 [1.4210166  0.7479841 ]
 [0.79239069 1.02656079]
 [2.25113858 1.04098539]]

Generations : 2
Parents
[[0.07493813 0.76172477]
 [0.81437176 0.4030058 ]]
Crossover
[[0.07493813 0.40300581]
 [0.81437176 0.76172477]
 [0.79239069 1.02656079]
 [0.81437176 0.76172477]]
Mutation
[[0.07493813 0.40300581]
 [0.81437176 0.76172477]
 [0.79239069 1.02656079]
 [0.81437176 0.7